# Site settings
title: Михаил &laquo;Kolo&raquo; Фёдоров
description: Михаил Фёдоров - Персональный блог
url: "/"
surl: "http://blog.fedorov.net"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "page/:num"
highlighter: pygments
gems: [jekyll-paginate]

disqus: fedorovnet

author: Mihail Fedorov
bio: Huge, smart & very sexy geek
email: mihail@fedorov.net
email_md5: 6ebbe5e1bcffca9ff468ad284575d516
twitter_username: 2mf
github_username: kolobus

# Theming options
# These settings are mandatory.
theme:              'blue-pink'
# drawer theming
drawer:
  text_color:       'grey-600'
  header_color:     'blue-500'
  navigation_color: 'grey-200'
# footer theming
footer:
  text_color: 'blue-grey-200'
  color: 'blue-grey-600'
